FROM usrc_tutorial_2_image:latest

RUN apt update
RUN apt install -y ros-melodic-vision-opencv
RUN apt install -y ros-melodic-rqt-image-view

# Copy in the files for the ball sorter packages
RUN mkdir /root/catkin_ws/src/ball_sorter_robot
COPY ball_sorter_robot /root/catkin_ws/src/ball_sorter_robot
RUN bash -c "cd ~/catkin_ws && source /opt/ros/melodic/setup.bash && catkin_make"

ENTRYPOINT bash /openvnc.sh;bash